---
- name: install packages
  apt:
    name:
      - mysql-server
      - libmysqlclient-dev
      - python3-pip
      - python3-dev
    update_cache: yes

- name: install pip modules
  pip:
    name:
      - mysql-python

- name: generate mysql root password
  shell:
    test -f /root/.my.cnf
    && (grep ^password /root/.my.cnf | head -1 | cut -d'"' -f2)
    || (cat /dev/urandom | tr -dc '[:alnum:]!#%&()*+,-./;<=>?@[]^_{|}~' | head -c 32)
  changed_when: False
  register: mysql_root_pass

- name: set mysql root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_pass.stdout }}"

- name: put .my.cnf
  template:
    src: root/.my.cnf.j2
    dest: /root/.my.cnf
    mode: '0600'

- name: set mysql root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass.stdout }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: generate server-id
  shell: hostname -I | sed -e 's/ /\n/' | grep -v '^$' | tail -1 | awk -F. '{print $3 * 256 + $4}'
  changed_when: False
  register: mysql_server_id

- name: put my.cnf
  template:
    src: "{{ item }}"
    dest: "/etc/mysql/mysql.conf.d/{{ item | basename | regex_replace('\\.j2$','') }}"
  with_fileglob:
    - ../templates/etc/mysql/mysql.conf.d/*.j2
  register: last_result

- name: restart mysql
  service:
    name: mysql
    state: restarted
  when: last_result.changed

- name: put dump file
  copy:
    src: tmp/mysqldump.sql.gz
    dest: /tmp/mysqldump.sql.gz
  changed_when: False

- name: check status of slaves
  mysql_replication:
    mode: getslave
  ignore_errors: true
  register: slave_status

- name: debug
  debug:
    var: slave_status

- name: stop replication
  mysql_replication: mode=stopslave
  when: slave_status.Is_Slave == False or slave_status.Slave_SQL_Running != "Yes"

- name: put .mysqlreplpass
  copy:
    src: tmp/.mysqlreplpass
    dest: /root/.mysqlreplpass
    mode: '0600'

- name: get mysql replication user password
  shell: cat /root/.mysqlreplpass
  changed_when: False
  register: mysql_repl_pass

- name: set replication
  mysql_replication:
    mode: changemaster
    master_host: "{{ mysql_repl_master }}"
    master_user: "{{ mysql_repl_user }}"
    master_password: "{{ mysql_repl_pass.stdout }}"
  when: slave_status.Is_Slave == False or slave_status.Slave_SQL_Running != "Yes"

- name: import dump file
  shell: zcat /tmp/mysqldump.sql.gz | mysql
  when: slave_status.Is_Slave == False or slave_status.Slave_SQL_Running != "Yes"

- name: start replication
  mysql_replication:
    mode: startslave
  when: slave_status.Is_Slave == False or slave_status.Slave_SQL_Running != "Yes"
