---
- hosts: allinone
  become: yes
  roles:
    - ubuntu18-common
    - mysql-master
    - postfix
    - postfixadmin
    - dovecot

- hosts: master
  become: yes
  roles:
    - ubuntu18-common
    - mysql-master
    - postfixadmin

- hosts: node
  become: yes
  roles:
    - ubuntu18-common
    - mysql-slave
    - postfix
    - dovecot
